id: P004388
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD89994
  title: ཉིང་ཁྲི་ས་ཁུལ་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    fa76b5f879824501ac4327d216cad510:
      image_group_id: I1PD90071
      title: ''
      volume_number: 1
      total_pages: 1134
      base_file: v001.txt
