id: IC066D801
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:57:21+00:00'
last_modified: '2022-06-07T22:30:39.901923+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD89994
  title: ཉིང་ཁྲི་ས་ཁུལ་གྱི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    61FA:
      image_group_id: I1PD90071
      title: ''
      total_pages: 1134
      order: 1
      base_file: 61FA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
